fix

diff --git a/Tooling/docker/vipm/Dockerfile b/Tooling/docker/vipm/Dockerfile
--- a/Tooling/docker/vipm/Dockerfile
+++ b/Tooling/docker/vipm/Dockerfile
@@ -8,9 +8,12 @@ RUN mkdir -p /usr/local/jki/vipm /etc/jki \
     && touch /usr/local/jki/vipm/Settings.ini /etc/jki/jki.conf
 
 ARG VIPM_DEB_URL="https://packages.jki.net/vipm/preview/vipm_latest_preview_amd64.deb"
-RUN wget -O /tmp/vipm.deb "$VIPM_DEB_URL" \
-    && dpkg -i /tmp/vipm.deb \
-    && rm /tmp/vipm.deb
+RUN set -e; \
+    wget -O /tmp/vipm.deb "$VIPM_DEB_URL" \
+    || (echo "Secure download failed, retrying without certificate verification..." >&2 \
+        && wget --no-check-certificate -O /tmp/vipm.deb "$VIPM_DEB_URL"); \
+    dpkg -i /tmp/vipm.deb; \
+    rm /tmp/vipm.deb
 
 RUN vipm help
 
